### ISSUE TITLE
Deprecation warnings with Ember 1.13.6

### ISSUE THREAD

**Issue by akisvolanis** [matixmatix/ember-parsley#1]
As Ember 1.13.6 has deprecate `Ember.View` and `Ember.keys`, there are many deprecation warnings.

**Comment by jurgenwerk** [comment]
I believe Ember now in newer versions allows custom HTML5 _data-*_ attributes, so you can freely use _data-parsley-*_ attributes without using this add-on (whose point was to allow usage of _data-parsley-*_ attributes in views in older Ember versions, where they were discarded). To get rid of deprecation messages, you could remove this add-on from your app, and instead add Parsley package to your bower packages and import it in your brocfile.

**Comment by akisvolanis** [comment]
Yeah that's what i've done, but i thought that was good to mention it. Thanks!
